### ISSUE TITLE
Make create device service resilient to paralel device creation with same activationId

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-push-server#681]
Steps to reproduce the issue:
Call push/device/create with the same `activationId`, that doesn't exist in the push server yet, multiple times in parallel.

Expected result:
A new record is created and updated several times - depending on the number of parallel calls.

Actual result:
One call creates a new record, others fail on unique constraint violation.

**Comment by banterCZ** [comment]
Consider Hibernate upsert https://vladmihalcea.com/hibernate-statelesssession-upsert/

**Comment by jnpsk** [comment]
🤔 It seems the Hibernate upsert expects the entity to have assigned id first [link](https://github.com/hibernate/hibernate-orm/blob/d085936fcb19ec43a7fcce59bf5e3a3e1ecd292b/hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java#L175-L183). Moreover the method is annotated with `@Incubating`, referring to the API being a "tech preview for early adopter who helps shape the final definition of the API."

**Comment by jnpsk** [comment]
Endpoint `push/device/create` creates a new device registration or updates the existing one (by activationId).  
In case of `N` simultaneous requests to create a new device registration with the same activationId, one of the request should trigger an insert to a database and the remaining `N-1` requests should tigger an update of the just inserted record. Ordering is not assured. None of the `N` request should fail because of constraint violation on activationId.

I made a simple test using:  
```
seq 1 5 | xargs -n1 -P5 curl -X 'POST' \                                                                                                    
  '$URL/powerauth-push-server/push/device/create' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "requestObject": {
    "appId": "$APP_ID",
    "token": "$TOKEN",
    "platform": "$PLATFORM",
    "activationId": "$ACTIVATION_ID"
  }
}'
```
Which run 5 parallel requests.
